---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-hd
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-hd-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        # PUSHOVER_TOKEN, RADARR__API_KEY
        key: radarr-hd
    - extract:
        # PUSHOVER_USER_KEY
        key: pushover
