ansible_become_pass: ENC[AES256_GCM,data:P9rxPx1pNaa6Pmeu,iv:r/PDeitL4VtQnHTa3rBsU2Ds3f11KxK21vU1N+iTp4A=,tag:/bFYwp6iLBffDdM3Ka87Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENE5lVWJIUjg4bmZrWGFv
            UCtCdnMyTlQ1Nm13dzg2WmZFY1poUHFiN0Y0CmcreUtZV0RMb2NHVGVrSXd1elVX
            cXFBUmF1OTM3cEVFL21uTFRvUmZJR2MKLS0tIEJORUFYeUZTMURVNkZJMWcrbk43
            Q05iVlQrdlhGaW8zZVp5Y3BxWjVMczAKxvXGixfbWebilzK1FfC34y4gLQi7lQnb
            mI1N6hHql/3ATXl9hMvyKJAZTTTXlLbiTrFfPVppyWvowBRgzycMAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T14:20:32Z"
    mac: ENC[AES256_GCM,data:8pOtQIT01cM8ktPdoG6dMG+KA3uEokMPzIkwCLMCgt0gQLJnSProEkJExrRaw/8kDDhVAXx9HDVfWD9Z0BnD4fmnQQ4Fa4Xdxedp+9gTbRHjoYMBU39ss1rQndBjc5pniuj9+hfWtaE6ZAuKZXGYtP5sgBpWmAv+5iukajivJks=,iv:vxWL6nsCUzwSKMEX/xSdYSkfmVrw3q/G/DWMnnS0eGQ=,tag:2yvsjtuGriNDjIFdxziHwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
