ansible_become_pass: ENC[AES256_GCM,data:UVw0J/kseFII33IZ,iv:5iIrnlR2OL20+YowVLrDXnsv+VWIIYBQVh0EgTqH0DI=,tag:acbnD1t5JXPK8vaKEcCg0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MHYyUTgxZFhlL1pJd0JE
            N2R3b3dSeDdpOW5SdW0vZmZzM3ZxK0ltYzFVCml0SmRBQjRibzBQVnhkNHJwcG9O
            V0gxREdWSWx3MTc5ZnBRM245Y2ErWTgKLS0tIGVpVWZZOWdjb2Y5c2dwZHkraXY5
            ajhsbTdvaENRSEVJY1NqSlVyS2JOUkkKiVGipZIymUT0HuK27KqQR4yhGUYOpmoZ
            9fUruT5AYbJ0fLcGd7TUt/D3BGNqDjG8VRf9bxP6qKA00kJ2ytUUoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T14:20:31Z"
    mac: ENC[AES256_GCM,data:UsFQI5zsWTalJUENDzIEtvaNoRdvgt5QRhNF8E0Uaa+m+BUW4pY0jiQitwXTybBtySUhqMcriE/pqy4DNuk5plkH1cYFwgeCTppEw9jgcmk47hdhze0mohztDisilSA4LpdKoGrRz7D1mnpdqzRk2VMZQsuIxYaujgZVAhw2mPY=,iv:tGM9apnwrV6FqF/ozbN/Ko2sCNXwZdwet7X1CdWKwrA=,tag:/Z0q35u4SqvvOTn3uYR3Dw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
