apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:ODEr3mbLndhQjA==,iv:zpSM1ra/jJn3GsR76hKgGhTkVip+cp06YJEiLie4UNc=,tag:sMwctRHtssNEPw+C8GjX7w==,type:str]
    admin-user: ENC[AES256_GCM,data:ioPUi9c=,iv:s9SfWCbWm2pKf7z1nC1fABF7r9m2zkhg5++pR70sA64=,tag:q3mi2YAkdNcepWtgYZcNgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpLzdzWmhSNFhiakhYS05K
            TDV3QjdHQlBPTm5IMXIrdnpITXpkSGxUMEFjCnZwOS9sSms2bEVpeHZqTlZRMngx
            NldyZVZ2YkFhS29RSDVCeXFCS3NyWTAKLS0tIDF3UHl4bWVFSjBveUpaQVIxcWV6
            S1pqYnc2UjlQbWMrRVk1MmEzVW9YbDAKaiCNstxicBYnKqCzrAD4jvIUH8AZ0Bzr
            P4xk6Tq00bHGLfhTiiCStoi9pbvRgjgUzUB097xIxaK/I1pTKAeptQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T14:22:43Z"
    mac: ENC[AES256_GCM,data:IrPxjkk5ve+ipw0eJ8EhKFuUJvYOyhCvD3gUch6Y0B2TNTSJkGaZ3snnPfbIvyp1ogkP9E3hHYdkKJgTXW78ym08n4h9Hvezl3tQBOskX67b6Y4kWQggntRLwuaKOxGHwIUb0Y9PQl1J76qR1YhW/VSBmUGa7JFZWzGnPttNNZ0=,iv:fnEyCHWw27fqsrXllYXfP8wRK4/45SR2rMcF2z/c9BI=,tag:3x2K6qVA2XMP1WmqnpHrig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
