---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-webhook-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: flux-webhook
        group: external
        url: https://flux-webhook.prymal.info
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
