apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Mgdh83Iupk1WyHFcjdrzm2/p5FJBOYpZ,iv:ElehY1AF2oVU9bnJSWQSAMjyTTFXhe8S7t9XstBdLws=,tag:F3uU+pD1VUyDRY9hc8QUyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd3NKcU0wSnZ2N2ZCQkdC
            aGdleGRSSnR1KzE5YU9yaGEwQVRkV1AwclRVCllkNDZ5ZVd3ZVhDdWk0Vy85ZkVI
            TGJEWmQySkp5LzlzalhLWEpOcGxaTTgKLS0tIFRQRGU1QTFzNDRoMkl1cnhDZ3d3
            MnAvOWRUdUlIb1l3aEVUTkpmSGVmbEUKhg+INkkti11khSQdUlr0Hc3oGlJ+dgFQ
            zW9qRatlCFX0/CXOk2aCsp3OIumQLXXo9PFr7XF+iKU6hkPiPX9WBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-16T13:22:06Z"
    mac: ENC[AES256_GCM,data:YOaknBEFk2cxVgaBrNhdpTmchBiL5+Ft1onBXKmd4/rl37888DohxzzqW/q0dS8q1JapDauxGp1yq4rd9Ro/85pj1ugastCs3bvHEg3T5DUFIJ0ZbikdXMM+PuO1s4MteCGDiFgBH+Htmb0AylHEgBfjayRvWUb4EclbP9f0iPw=,iv:IALWNFjnBHw2F8539z1PnLpgEyBX4jDAsalTt9agOic=,tag:8Fwc9Y7jpZ3m/N2Cc2XyKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
