---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unpackerr-hd
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.12.0@sha256:b2838a40b8c892a371f7d3ccdf72a983ff666cf9f0fa4e72f4c34c431559980d
    env:
      TZ: America/Denver
      UN_SONARR_0_URL: http://sonarr-hd.default.svc.cluster.local
      UN_SONARR_0_PATHS_0: /complete/sonarr-hd
      UN_RADARR_0_URL: http://radarr-hd.default.svc.cluster.local
      UN_RADARR_0_PATHS_0: /complete/radarr-hd
    envFrom:
      - secretRef:
          name: unpackerr-hd-secret
    service:
      main:
        enabled: false
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    persistence:
      complete:
        enabled: true
        type: nfs
        server: 10.10.1.30
        path: /volume1/data/media/downloads/complete
        mountPath: /complete
    resources:
      requests:
        cpu: 5m
        memory: 250Mi
      limits:
        memory: 5000Mi
