---
originRequest:
  http2Origin: true

ingress:
  - hostname: prymal.info
    service: https://ingress-nginx-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: ingress.prymal.info
  - hostname: "*.prymal.info"
    service: https://ingress-nginx-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: ingress.prymal.info
  - service: http_status:404
