---
apiVersion: v1
kind: ConfigMap
metadata:
  name: theme-park-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: theme-park
        group: "Web - Internal"
        url: https://theme-park.prymal.info
        interval: 1m
        client:
          dns-resolver: tcp://10.10.1.31:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
