---
# https://github.com/kevincoakley/ansible-role-k8s-rolling-update
- name: Cluster rollout update
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  serial: 1
  pre_tasks:
    - name: Pausing for 5 seconds...
      ansible.builtin.pause:
        seconds: 5
  tasks:
    - name: Get the node's details
      ansible.builtin.command: "kubectl get node {{ inventory_hostname }} -o json"
      register: kubectl_get_node
      delegate_to: "{{ groups['master'][0] }}"
      failed_when: false
      changed_when: false

    - name: Update node
      when:
        # When status.conditions[x].type == Ready then check stats.conditions[x].status for True|False
        - kubectl_get_node['stdout'] | from_json | json_query("status.conditions[?type == 'Ready'].status")
        # If spec.unschedulable is defined then the node is cordoned
        - not (kubectl_get_node['stdout'] | from_json).spec.unschedulable is defined
      block:
        - name: "Cordon {{ inventory_hostname }}"
          kubernetes.core.k8s_drain:
            name: "{{ inventory_hostname }}"
            kubeconfig: /etc/rancher/k3s/k3s.yaml
            state: cordon
          delegate_to: "{{ groups['master'][0] }}"

        - name: "Drain {{ inventory_hostname }}"
          ansible.builtin.command: "kubectl drain --pod-selector='app!=rook-ceph-osd,app!=csi-attacher,app!=csi-provisioner' --ignore-daemonsets --delete-emptydir-data --force --grace-period=120 {{ inventory_hostname }}"
          delegate_to: "{{ groups['master'][0] }}"
          changed_when: false

        # - name: "Drain {{ inventory_hostname }}"
        #   kubernetes.core.k8s_drain:
        #     name: "{{ inventory_hostname }}"
        #     kubeconfig: /etc/rancher/k3s/k3s.yaml
        #     state: drain
        #     delete_options:
        #       delete_emptydir_data: true
        #       ignore_daemonsets: true
        #       terminate_grace_period: 600
        #       wait_timeout: 900
        #       force: true
        #   # Supported feature in upcoming kubernetes.core 2.5.0
        #   #  pod_selectors:
        #   #    - app!=rook-ceph-osd
        #   #    - app!=csi-attacher
        #   #    - app!=csi-provisioner
        #   delegate_to: "{{ groups['master'][0] }}"

        - name: Update all packages
          ansible.builtin.apt:
            upgrade: dist
            update_cache: true

        - name: Check if a Reboot is Required
          ansible.builtin.stat:
            path: /var/run/reboot-required
          register: reboot_required

        - name: Reboot
          ansible.builtin.reboot:
            msg: Rebooting node
            post_reboot_delay: 60
            reboot_timeout: 3600
          when: reboot_required.stat.exists

        - name: "Uncordon {{ inventory_hostname }}"
          kubernetes.core.k8s_drain:
            name: "{{ inventory_hostname }}"
            kubeconfig: /etc/rancher/k3s/k3s.yaml
            state: uncordon
          delegate_to: "{{ groups['master'][0] }}"
