---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-server-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: echo-server
        group: "Web - External"
        url: https://echo-server.prymal.info
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
