---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "prymal-info-production-production"
  namespace: networking
spec:
  secretName: "prymal-info-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "prymal.info"
  dnsNames:
    - "prymal.info"
    - "*.prymal.info"
