---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "prymal-info-production-staging"
  namespace: networking
spec:
  secretName: "prymal-info-production-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "prymal.info"
  dnsNames:
    - "prymal.info"
    - "*.prymal.info"
