---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: prometheus
        group: internal
        url: https://prometheus.prymal.info
        interval: 1m
        client:
          dns-resolver: tcp://10.10.1.31:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-mamanger-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: alert-mamanger
        group: internal
        url: https://alert-mamanger.prymal.info
        interval: 1m
        client:
          dns-resolver: tcp://10.10.1.31:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
