---
# Instance Definition
# This section defines your instance type, name, and authentication
# Documentation: https://recyclarr.dev/wiki/yaml/config-reference/#basic
radarr:
  movie-hd-bluray-web:
    base_url: http://radarr-hd.default.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

    custom_formats:
      # Movie Versions
      - trash_ids:
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        quality_profiles:
          - name: HD Bluray + WEB
            score: 0

# Instance Definition
# This section defines your instance type, name, and authentication
# Documentation: https://recyclarr.dev/wiki/yaml/config-reference/#basic
sonarr:
  web-1080p-v4:
    base_url: http://sonarr-hd.default.svc.cluster.local
    api_key: !env_var SONARR_API_KEY

    include:
      # Comment out any of the following includes to disable them
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
