---
name: "Draft Release"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@0914d50df753bbc42180d982a6550f195390069f # v2.0.0
        id: generate-token
        with:
          app_id: "${{ secrets.APP_ID }}"
          private_key: "${{ secrets.PRIVATE_KEY }}"

      - uses: release-drafter/release-drafter@65c5fb495d1e69aa8c08a3317bc44ff8aabe9772 # v5.24.0
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
